galaxy_info:
  author: Rene Orozco (@rene-orozco)
  description: Create Fusion backup policies for recipes to MAS related application
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
